#!/usr/bin/env bash

# little util for firing up rust-lldb - probably only works for very simple projects

set -e

# you would really think there would be an easier way of getting the name of the project...

project_metadata=$(cargo metadata --format-version 1)
project_name=$(echo "$project_metadata" | jq '.workspace_members | .[0]' --raw-output | cut -d' ' -f1)
target_directory=$(echo "$project_metadata" | jq .target_directory --raw-output)
built_file="$target_directory/debug/$project_name"
rust-lldb "$built_file"
